providers = ["python"]

[phases.setup]
aptPkgs = ["ffmpeg", "nodejs", "npm"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "npm install -g ejs",
  "npm install -g youtube-po-token-generator"
]